### ISSUE TITLE
wide tables

### ISSUE THREAD

**Issue by emicklei** [calyptia/go-bubble-table#7]
If a table contains many and/or wide columns, the data is not complete visible in the viewport of the window.

In order to let the user view those hidden columns on the right, it would require the feature to do horizontal scrolling (cursor left and right).

Below is a snapshot of your modified example code. I have repeated the columns 5 times to demonstrate it.

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/686220/163726918-69f50785-3b55-42cd-b979-89b6a2d8b87b.png">

**Comment by nicolasparada** [comment]
Thanks for opening the issue. 
I'll look on how to implement horizontal scrolling.

This table bubble uses the viewport bubble internally so we may need to tackle the issue there maybe 🤔

**Comment by emicklei** [comment]
👍  great

**Comment by emicklei** [comment]
Currently, scrolling is by single character (left, right) ; it may take a time to see the last column values.

Would be nice to support the behaviour of what could be called PageLeft, PageRight, HomeLeft and EndRight.

For example `shift + ←` PageLeft,  `option + →` for EndRight etc.

WDYT?

**Comment by nicolasparada** [comment]
Yeah, it is a little bit slow.
I'll check what we can do ;)
